# Generated by Django 5.1.2 on 2024-11-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_V0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrideuser',
            name='licence_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/licence/'),
        ),
        migrations.AddField(
            model_name='xrideuser',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/national_id/'),
        ),
        migrations.AddField(
            model_name='xrideuser',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/personal/'),
        ),
    ]
