# Generated by Django 5.1.2 on 2024-11-01 14:28

import Auth_V0.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_V0', '0004_alter_xrideuser_licence_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrideuser',
            name='licence_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Auth_V0.models.licence_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='xrideuser',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Auth_V0.models.national_id_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='xrideuser',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Auth_V0.models.personal_photo_upload_path),
        ),
    ]
